// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCulbH2blxZTAsuMDFHGdYezoD_GMMs28A',
    appId: '1:304739136532:web:47601d647767a7f5bbe301',
    messagingSenderId: '304739136532',
    projectId: 'calendar-app-83402',
    authDomain: 'calendar-app-83402.firebaseapp.com',
    storageBucket: 'calendar-app-83402.firebasestorage.app',
    measurementId: 'G-GH3V40Y3GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDI6Lo-4js7CP5bhaVrTVbNsv8OTcSAY8',
    appId: '1:304739136532:android:52beab639bab9df5bbe301',
    messagingSenderId: '304739136532',
    projectId: 'calendar-app-83402',
    storageBucket: 'calendar-app-83402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRoxtJK13alZ1AuEqAv5-2suyk0Gu44ro',
    appId: '1:304739136532:ios:049236bd5b15552cbbe301',
    messagingSenderId: '304739136532',
    projectId: 'calendar-app-83402',
    storageBucket: 'calendar-app-83402.firebasestorage.app',
    iosBundleId: 'com.example.calendarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRoxtJK13alZ1AuEqAv5-2suyk0Gu44ro',
    appId: '1:304739136532:ios:049236bd5b15552cbbe301',
    messagingSenderId: '304739136532',
    projectId: 'calendar-app-83402',
    storageBucket: 'calendar-app-83402.firebasestorage.app',
    iosBundleId: 'com.example.calendarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCulbH2blxZTAsuMDFHGdYezoD_GMMs28A',
    appId: '1:304739136532:web:14853f0b0b6cc918bbe301',
    messagingSenderId: '304739136532',
    projectId: 'calendar-app-83402',
    authDomain: 'calendar-app-83402.firebaseapp.com',
    storageBucket: 'calendar-app-83402.firebasestorage.app',
    measurementId: 'G-FSMV598V5R',
  );
}
